#include "rules.h"
#include "renderer.h"
#include <stdio.h>

static void json_string(const char *s)
{
    putchar('"');
    for (; *s; ++s) {
        unsigned char c = (unsigned char)*s;
        if (c == '"' || c == '\\') { putchar('\\'); putchar(c); }
        else if (c < 32 || c == '<') printf("\\u%04x", c);
        else putchar(c);
    }
    putchar('"');
}

/* Export compiled C tables, including NOOP entries, rather than parsing C. */
int main(void)
{
    puts("// Generated by make rule-catalog; do not edit by hand.\nglobalThis.TURMITE_RULES = [");
    for (size_t i = 0; i < rules_count(); ++i) {
        const TurmiteRule *r = rules_get(i);
        printf("%s{\"id\":", i ? ",\n" : ""); json_string(r->id);
        printf(",\"name\":"); json_string(r->name);
        printf(",\"states\":%u,\"colors\":%u,\"table\":[", r->states, r->colors);
        for (unsigned s = 0; s < r->states; ++s) {
            printf("%s[", s ? "," : "");
            for (unsigned c = 0; c < r->colors; ++c) {
                const RuleAction *a = &r->table[s][c];
                printf("%s{\"w\":%u,\"t\":\"%s\",\"n\":%u,\"halt\":%s}",
                       c ? "," : "", a->write_color, turn_name(a->turn), a->next_state, a->halt ? "true" : "false");
            }
            putchar(']');
        }
        printf("]}");
    }
    puts("\n];\nglobalThis.TURMITE_PALETTE = [");
    for (size_t c = 0; c < TURMITE_COLORS; ++c) printf("%s%u", c ? "," : "", RENDER_BASE_PALETTE[c]);
    puts("];");
    return ferror(stdout) ? 1 : 0;
}
